# Generated by Django 4.1 on 2023-10-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_agent_contract_node_type_objecthistory_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='final_value',
            field=models.IntegerField(blank=True, help_text='Введите конечное показание счетчика', null=True, verbose_name='Конечное показание счетчика'),
        ),
    ]
