# Generated by Django 4.1 on 2023-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_object_final_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='final_value',
            field=models.IntegerField(blank=True, help_text='Введите конечное показание счетчика', null=True, verbose_name='Конечное показание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='start_value',
            field=models.IntegerField(default=0, help_text='Введите начальное показание счетчика', verbose_name='Начальное показание'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='final_value',
            field=models.IntegerField(help_text='Введите конечное показание счетчика', verbose_name='Конечное показание'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='start_value',
            field=models.IntegerField(help_text='Введите начальное показание счетчика', verbose_name='Начальное показание'),
        ),
    ]
