# Generated by Django 4.1 on 2023-10-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_object_final_value_alter_object_start_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='Введите имя исполнителя', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Введите отчество исполнителя', max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(help_text='Введите номер телефона исполнителя', max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='surname',
            field=models.CharField(help_text='Введите фамилию исполнителя', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_issue',
            field=models.DateField(help_text='Введите дату оформления договора', verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(help_text='Введите номер договора', max_length=100, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=True, help_text='Выберите статус договора', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='node',
            name='address',
            field=models.CharField(help_text='Введите адрес объекта', max_length=200, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='Введите имя объекта', max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.BooleanField(default=True, help_text='Выберите статус объекта', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(help_text='Введите адрес объекта', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='object',
            name='code',
            field=models.CharField(help_text='Введите код объекта', max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='object',
            name='contract',
            field=models.ForeignKey(help_text='Выберите договор объекта', on_delete=django.db.models.deletion.PROTECT, related_name='contract_object', to='mainsite.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='object',
            name='node',
            field=models.ForeignKey(help_text='Выберите узел объекта', on_delete=django.db.models.deletion.PROTECT, related_name='node_object', to='mainsite.node', verbose_name='Узел'),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.BooleanField(default=True, help_text='Выберите статус объекта', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.ForeignKey(help_text='Выберите тип объекта', on_delete=django.db.models.deletion.PROTECT, related_name='type_object', to='mainsite.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='address',
            field=models.CharField(help_text='Введите адрес объекта', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='code',
            field=models.CharField(help_text='Введите код объекта', max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='contract',
            field=models.ForeignKey(help_text='Выберите договор объекта', on_delete=django.db.models.deletion.PROTECT, related_name='contract_objecthistory', to='mainsite.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='month',
            field=models.IntegerField(help_text='Введите месяц показания', verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='node',
            field=models.ForeignKey(help_text='Выберите узел объекта', on_delete=django.db.models.deletion.PROTECT, related_name='node_objecthistory', to='mainsite.node', verbose_name='Узел'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='status',
            field=models.BooleanField(default=True, help_text='Выберите статус объекта', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='type',
            field=models.ForeignKey(help_text='Выберите тип объекта', on_delete=django.db.models.deletion.PROTECT, related_name='type_objecthistory', to='mainsite.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='objecthistory',
            name='year',
            field=models.IntegerField(help_text='Введите год показания', verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='Введите тип объекта', max_length=100, unique=True, verbose_name='Тип'),
        ),
    ]
