# Generated by Django 4.1 on 2023-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_alter_agent_name_alter_agent_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecthistory',
            name='code',
            field=models.CharField(help_text='Введите код объекта', max_length=100, verbose_name='Код'),
        ),
    ]
